=== chiemeliecoder/sql_musicmarketplacexml/src/main/resources/musicdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="musicdata.xsd">
    <xs:element name="MusicMarketplace">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Users" type="UsersType"/>
                <xs:element name="Artists" type="ArtistsType"/>
                <xs:element name="Albums" type="AlbumsType"/>
                <xs:element name="Playlists" type="PlaylistsType"/>
                <xs:element name="Wishlists" type="WishlistsType"/>
                <xs:element name="UserProfiles" type="UserProfilesType"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="UsersType">
        <xs:sequence>
            <xs:element name="User" type="UserType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserType">
        <xs:sequence>
            <xs:element name="UserId" type="xs:int"/>
            <xs:element name="Username" type="xs:string"/>
            <xs:element name="Email" type="xs:string"/>
            <xs:element name="Password" type="xs:string"/>
            <xs:element name="UserProfile" type="UserProfileType"/>
            <xs:element name="Playlists" type="PlaylistsType"/>
            <xs:element name="Wishlists" type="WishlistsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ArtistsType">
        <xs:sequence>
            <xs:element name="Artist" type="ArtistType" minOccurs="0" maxOccurs="unbounded"/>

        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ArtistType">
        <xs:sequence>
            <xs:element name="ArtistId" type="xs:int"/>
            <xs:element name="ArtistName" type="xs:string"/>
            <xs:element name="Album" type="AlbumType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AlbumsType">
        <xs:sequence>
            <xs:element name="Album" type="AlbumType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="AlbumType">
        <xs:sequence>
            <xs:element name="AlbumId" type="xs:int"/>
            <xs:element name="AlbumTitle" type="xs:string"/>
            <xs:element name="ReleaseDate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PlaylistsType">
        <xs:sequence>
            <xs:element name="Playlist" type="PlaylistType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PlaylistType">
        <xs:sequence>
            <xs:element name="PlaylistId" type="xs:int"/>
            <xs:element name="PlaylistName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="WishlistType">
        <xs:sequence>
            <xs:element name="WishlistId" type="xs:int"/>
            <xs:element name="Name" type="xs:string"/>
            <xs:element name="Albums" type="AlbumsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="WishlistsType">
        <xs:sequence>
            <xs:element name="Wishlist" type="WishlistType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Wishlists" type="WishlistsType"/>

    <xs:complexType name="UserProfilesType">
        <xs:sequence>
            <xs:element name="UserProfile" type="UserProfileType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="UserProfileType">
        <xs:sequence>
            <xs:element name="Id" type="xs:int"/>
            <xs:element name="Bio" type="xs:string"/>
            <xs:element name="ProfileImage" type="xs:string"/>
            <xs:element name="Location" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== chiemeliecoder/sql_musicmarketplacexml/src/main/resources/musicdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<MusicMarketplace xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="musicdata.xsd">
    <Users>
        <User>
            <UserId>1</UserId>
            <Username>john123</Username>
            <Email>john@example.com</Email>
            <Password>password</Password>
        </User>
    </Users>
    <Artists>
        <Artist>
            <ArtistId>1</ArtistId>
            <ArtistName>John Doe</ArtistName>
        </Artist>
    </Artists>
    <Albums>
        <Album>
            <AlbumId>1</AlbumId>
            <AlbumTitle>Album 1</AlbumTitle>
            <ReleaseDate>2022-01-01</ReleaseDate>
        </Album>
    </Albums>
    <Playlists>
        <Playlist>
            <PlaylistId>1</PlaylistId>
            <PlaylistName>My Playlist</PlaylistName>
        </Playlist>
    </Playlists>
    <Wishlist>
        <WishlistId>1</WishlistId>
    </Wishlist>
    <UserProfiles>
        <UserProfile>
            <Id>1</Id>
            <Bio>User bio</Bio>
            <ProfileImage>profile.jpg</ProfileImage>
            <Location>Location</Location>
        </UserProfile>
    </UserProfiles>
</MusicMarketplace>
