=== chiemeliecoder/sql_musicmarketplacexml/target/classes/musicdata.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="MusicData">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Users">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="User" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="UserId" type="xs:int"/>
                                        <xs:element name="Username" type="xs:string"/>
                                        <xs:element name="Email" type="xs:string"/>
                                        <xs:element name="Password" type="xs:string"/>
                                        <xs:element name="Playlists">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Playlist" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="PlaylistId" type="xs:int"/>
                                                                <xs:element name="PlaylistName" type="xs:string"/>
                                                                <xs:element name="Tracks">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element ref="Track" minOccurs="0" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Purchases">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Purchase" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="PurchaseId" type="xs:int"/>
                                                                <xs:element ref="Track"/>
                                                                <xs:element name="PurchaseDate" type="xs:date"/>
                                                                <xs:element name="Price" type="xs:decimal"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Reviews">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Review" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="ReviewId" type="xs:int"/>
                                                                <xs:element ref="Album"/>
                                                                <xs:element name="Rating" type="xs:int"/>
                                                                <xs:element name="Comment" type="xs:string"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Wishlist" minOccurs="0">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="WishlistId" type="xs:int"/>
                                                    <xs:element ref="Album"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Artists">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Artist" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ArtistId" type="xs:int"/>
                                        <xs:element name="ArtistName" type="xs:string"/>
                                        <xs:element name="Biography" type="xs:string"/>
                                        <xs:element name="Albums">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="Album" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="AlbumId" type="xs:int"/>
                                                                <xs:element name="AlbumTitle" type="xs:string"/>
                                                                <xs:element name="ReleaseDate" type="xs:date"/>
                                                                <xs:element name="Tracks">
                                                                    <xs:complexType>
                                                                        <xs:sequence>
                                                                            <xs:element ref="Track" minOccurs="0" maxOccurs="unbounded"/>
                                                                        </xs:sequence>
                                                                    </xs:complexType>
                                                                </xs:element>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Genres">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element ref="Genre" minOccurs="0" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="Achievements">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="ArtistAchievement" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="AchievementId" type="xs:int"/>
                                                                <xs:element name="AchievementTitle" type="xs:string"/>
                                                                <xs:element name="AchievementDate" type="xs:date"/>
                                                            </xs:sequence>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Genres">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Genre" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="GenreId" type="xs:int"/>
                                        <xs:element name="GenreName" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Track">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="TrackId" type="xs:int"/>
                            <xs:element name="TrackTitle" type="xs:string"/>
                            <xs:element name="Duration" type="xs:duration"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Album">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="AlbumId" type="xs:int"/>
                            <xs:element name="AlbumTitle" type="xs:string"/>
                            <xs:element name="ReleaseDate" type="xs:date"/>
                            <xs:element ref="Artist"/>
                            <xs:element name="Tracks">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="Track" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Playlist">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PlaylistId" type="xs:int"/>
                            <xs:element name="PlaylistName" type="xs:string"/>
                            <xs:element ref="User"/>
                            <xs:element name="Tracks">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="Track" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Purchase">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="PurchaseId" type="xs:int"/>
                            <xs:element ref="User"/>
                            <xs:element ref="Track"/>
                            <xs:element name="PurchaseDate" type="xs:date"/>
                            <xs:element name="Price" type="xs:decimal"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Review">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="ReviewId" type="xs:int"/>
                            <xs:element ref="User"/>
                            <xs:element ref="Album"/>
                            <xs:element name="Rating" type="xs:int"/>
                            <xs:element name="Comment" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Wishlist">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="WishlistId" type="xs:int"/>
                            <xs:element ref="User"/>
                            <xs:element ref="Album"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="Genre">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="GenreId" type="xs:int"/>
                            <xs:element name="GenreName" type="xs:string"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ArtistAchievement">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="AchievementId" type="xs:int"/>
                            <xs:element ref="Artist"/>
                            <xs:element name="AchievementTitle" type="xs:string"/>
                            <xs:element name="AchievementDate" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== chiemeliecoder/sql_musicmarketplacexml/target/classes/musicdata.xml
<?xml version="1.0" encoding="UTF-8"?>
<MusicData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="musicdata.xsd">
    <Users>
        <User>
            <UserId>1</UserId>
            <Username>john123</Username>
            <Email>john@example.com</Email>
            <Password>password</Password>
            <Playlists>
                <Playlist>
                    <PlaylistId>1</PlaylistId>
                    <PlaylistName>My Playlist</PlaylistName>
                    <Tracks>
                        <Track>
                            <TrackId>1</TrackId>
                            <TrackTitle>Track 1</TrackTitle>
                            <Duration>PT3M45S</Duration>
                        </Track>
                        <Track>
                            <TrackId>2</TrackId>
                            <TrackTitle>Track 2</TrackTitle>
                            <Duration>PT4M12S</Duration>
                        </Track>
                    </Tracks>
                </Playlist>
            </Playlists>
            <Purchases>
                <Purchase>
                    <PurchaseId>1</PurchaseId>
                    <Track>
                        <TrackId>1</TrackId>
                        <TrackTitle>Track 1</TrackTitle>
                        <Duration>PT3M45S</Duration>
                    </Track>
                    <PurchaseDate>2023-06-08</PurchaseDate>
                    <Price>9.99</Price>
                </Purchase>
            </Purchases>
            <Reviews>
                <Review>
                    <ReviewId>1</ReviewId>
                    <Album>
                        <AlbumId>1</AlbumId>
                        <AlbumTitle>Album 1</AlbumTitle>
                        <ReleaseDate>2022-01-01</ReleaseDate>
                    </Album>
                    <Rating>5</Rating>
                    <Comment>This album is amazing!</Comment>
                </Review>
            </Reviews>
            <Wishlist>
                <WishlistId>1</WishlistId>
                <Album>
                    <AlbumId>2</AlbumId>
                    <AlbumTitle>Album 2</AlbumTitle>
                    <ReleaseDate>2023-05-01</ReleaseDate>
                </Album>
            </Wishlist>
        </User>
    </Users>
    <Artists>
        <Artist>
            <ArtistId>1</ArtistId>
            <ArtistName>John Doe</ArtistName>
            <Biography>...</Biography>
            <Albums>
                <Album>
                    <AlbumId>1</AlbumId>
                    <AlbumTitle>Album 1</AlbumTitle>
                    <ReleaseDate>2022-01-01</ReleaseDate>
                    <Tracks>
                        <Track>
                            <TrackId>1</TrackId>
                            <TrackTitle>Track 1</TrackTitle>
                            <Duration>PT3M45S</Duration>
                        </Track>
                        <Track>
                            <TrackId>2</TrackId>
                            <TrackTitle>Track 2</TrackTitle>
                            <Duration>PT4M12S</Duration>
                        </Track>
                    </Tracks>
                </Album>
            </Albums>
            <Genres>
                <Genre>
                    <GenreId>1</GenreId>
                    <GenreName>Rock</GenreName>
                </Genre>
                <Genre>
                    <GenreId>2</GenreId>
                    <GenreName>Pop</GenreName>
                </Genre>
            </Genres>
            <Achievements>
                <ArtistAchievement>
                    <AchievementId>1</AchievementId>
                    <AchievementTitle>Achievement 1</AchievementTitle>
                    <AchievementDate>2023-01-01</AchievementDate>
                </ArtistAchievement>
            </Achievements>
        </Artist>
    </Artists>
    <Genres>
        <Genre>
            <GenreId>1</GenreId>
            <GenreName>Rock</GenreName>
        </Genre>
        <Genre>
            <GenreId>2</GenreId>
            <GenreName>Pop</GenreName>
        </Genre>
    </Genres>
</MusicData>

    </Tracks>
</MusicMarketplace>
